# Generated by Django 5.0.2 on 2024-04-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnews',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
