# Generated by Django 5.0.4 on 2024-04-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_alter_createnews_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='createnews',
            name='creation_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
